const app = require('express')();
const PORT = 8080;
const cors = require('cors');
const axios = require('axios');
const bodyParser = require('body-parser');
app.use(cors());
app.use(bodyParser.json());

app.listen(
    PORT,
    () => console.log(`Server is running on port ${PORT}`)
)

app.get('/team', (req, res) => {
    res.status(200).send([
        {
            name: 'Karim Mejri',
            image: 'team1.jpg',
            prof: 'Culinary Expert'
        },
        {
            name: 'Mehdi Ayadi',
            image: 'team2.png',
            prof: 'Food Photographer'
        },
        {
            name: 'Wafa Oueslati',
            image: 'team3.png',
            prof: 'Recipe Developer'
        },
        {
            name: 'Yosr Aloui',
            image: 'team4.jpg',
            prof: 'Nutritionist'
        },
        {
            name: 'Adam Ben Ali',
            image: 'team5.jpg',
            prof: 'Food Writer'
        },
        {
            name: 'Nesrine Tlili',
            image: 'team6.jpg',
            prof: 'Web Developer'
        },
        {
            name: 'Omar Ben Salah',
            image: 'team7.jpg',
            prof: 'Social Media Manager'
        },
        {
            name: 'Mariam Yahyaoui',
            image: 'team8.png',
            prof: 'Community Manager'
        },
    ])
})
app.get('/recipes', (req, res) => {
    res.status(200).send([
        {
            id: '156248',
            name: 'Chicken Enchiladas',
            cuisine: 'Mexican',
            description: 'This chicken enchilada recipe is easy to make with tortillas, tender chicken, and a deliciously cheesy sauce for a family-pleasing Mexican meal.',
            prepTime: '15 mins',
            cookTime: '35 mins',
            totalTime: '50 mins',
            Servings: '8',
            yield: '8 enchiladas',
            firstStep: 'Cook the chicken, slice it into cubes, then return it to the skillet.',
            secondStep: 'Add the onion, a cup of cheese, sour cream, and dried herbs.',
            thirdStep: 'Melt the cheese. Stir in tomato sauce, green pepper, garlic, chili powder, and salt.',
            fourthStep: 'Fill the enchiladas and roll them up. Arrange them in a baking dish.',
            fifthStep: 'Top with taco sauce and remaining cheese. Bake until the cheese is melted.',
            cookLong: 'In an oven preheated to 350 degrees F, these chicken enchiladas should be perfectly cooked in about 20 minutes. You’ll know the enchiladas are done when they are heated through and the cheese is melted. ',
            ingredients: '1 tablespoon olive oil or as needed,4 skinless, boneless chicken breast halves ,1 onion, chopped ,1 ¾ cups shredded Cheddar cheese divided ,½ pint sour cream ,1 tablespoon dried parsley ,½ teaspoon dried oregano ,½ teaspoon ground black pepper ,1 (15 ounce) can tomato sauce ,⅓ cup chopped green bell pepper ,1 clove garlic minced ,1 tablespoon chili powder, ½ teaspoon salt (Optional), ½ cup water (Optional) ,8 (10 inch) flour tortillas,1 (12 ounce) jar taco sauce',
            Calories: '498',
            Fat: '16',
            Carbs: '50',
            Protein: '27',
            photo: 'chicken.png',
            Rate: '4.5',
            video: 'https://www.youtube.com/watch?v=8u2_RmrkD_g',
            comment: [{
                
            }],
            type: 'latest',
        }, {
            id: '156249',
            cuisine: 'Italian',
            name: 'Easy Air Fryer Pork Chops',
            description: 'Boneless pork chops cooked to perfection in the air fryer. This recipe is so easy and you couldnt ask for a more tender and juicy chop.',
            prepTime: '5 mins',
            cookTime: '20 mins',
            totalTime: '25 mins',
            Servings: '4',
            yield: '',
            firstStep: 'Preheat the air fryer to 380 degrees F (190 degrees C).',
            secondStep: 'Combine Parmesan cheese, paprika, garlic powder, salt, parsley, and pepper in a flat shallow dish; mix well.',
            thirdStep: 'Coat each pork chop with olive oil. Dredge both sides of each chop in the Parmesan mixture and set on a plate.',
            fourthStep: 'Place 2 chops in the basket of the air fryer and cook for 10 minutes; flipping halfway through cook time. Transfer to a cutting board and let rest for 5 minutes. Repeat with remaining chops.',
            fifthStep: 'Served hot and enjoy!',
            cookLong: 'This recipe should completely cook medium-sized pork chops in about 10 minutes in an air fryer set to 380 degrees F. Of course, since pork chops vary in thickness, its best to test the temperature before you dig in. An instant read food thermometer inserted into the thickest part of the chop should read at least 145 degrees F.',
            ingredients: '½ cup grated Parmesan cheese, 1 teaspoon paprika, 1 teaspoon garlic powder, 1 teaspoon kosher salt, 1 teaspoon dried parsley, ½ teaspoon ground black pepper, 4 (5 ounce) boneless pork chop ,2 tablespoons extra virgin olive oil',
            Calories: '',
            Fat: '',
            Carbs: '',
            Protein: '',
            photo: 'Fryer.png',
            Rate: '3.5',
            video: 'https://www.youtube.com/watch?v=NRavw8954uk',
            comment: [{
            }],
            type: 'latest',

        },
        {
            id: '156250',
            name: 'Stir-Fried Ginger Broccoli Beef',
            cuisine: 'Mexican',
            description: 'Tender beef slices and crunchy Chinese broccoli or kale are stir-fried in a savory ginger sauce. Easy to make, pretty healthy, and everybody loves it!',
            prepTime: '25 mins',
            cookTime: '10 mins',
            totalTime: '55 mins',
            Servings: '3',
            yield: '3 servings',
            firstStep: 'Toss beef strips with 1 teaspoon chicken bouillon granules and 3/4 teaspoon sugar in a bowl. Marinate in the refrigerator, 20 minutes to 1 hour.',
            secondStep: 'Combine remaining 1/4 teaspoon chicken bouillon granules, 1/4 teaspoon sugar, and ginger juice in a bowl.',
            thirdStep: 'Mix 2 tablespoons water with cornstarch in a small bowl. Add to bowl with ginger juice mixture; stir.',
            fourthStep: 'Heat 1 tablespoon oil in a wok over medium-high heat; cook and stir ginger until fragrant, about 30 seconds. Add broccoli; cook and stir for 2 minutes. Add remaining 1 tablespoon water, cover, and cook until broccoli is cooked but still crunchy, about 1 minute. Transfer to a dish.',
            fifthStep: 'Heat remaining 1 tablespoon oil in the wok. Add beef; cook and stir to medium well doneness, about 4 minutes. Add ginger juice mixture and broccoli. Cook and stir until heated through, about 2 minutes.',
            cookLong: 'This recipe should completely cook medium-sized pork chops in about 10 minutes in an air fryer set to 380 degrees F. Of course, since pork chops vary in thickness, its best to test the temperature before you dig in. An instant read food thermometer inserted into the thickest part of the chop should read at least 145 degrees F.',
            ingredients: '7 ounces beef sirloin, sliced into strips,1 ¼ teaspoons chicken bouillon granules divided, 1 teaspoon white sugar divided ,1 tablespoon ginger juice, 3 tablespoons water divided, 1 teaspoon cornstarch, 2 tablespoons vegetable oil divided ,1 (4 inch) piece ginger root  peeled and sliced ,14 ounces Chinese broccoli sliced',
            Calories: '',
            Fat: '',
            Carbs: '',
            Protein: '',
            photo: 'Ginger.png',
            Rate: '5',
            video: 'https://www.youtube.com/watch?v=uej-n2JxIQo',
            comment: [{
            }],
            type: 'latest',
        }, {
            id: '156251',
            name: 'Chef Johns Meatball-Inspired Meatloaf',
            cuisine: 'Frensh',
            description: 'The main point of this Italian meatball-inspired meatloaf is to show you what happens when you make meatloaf like your grandparents did.',
            prepTime: '20 mins',
            cookTime: '1 hr 15 mins',
            totalTime: '2 hrs',
            Servings: '10',
            yield: '1 meatloaf',
            firstStep: 'Preheat oven to 325 degrees F (165 degrees C). Grease a 9x13-inch baking dish.',
            secondStep: 'Heat olive oil and butter together in a large skillet over medium-high heat. Saute onion with a pinch of salt in hot oil and butter until onion is golden brown and soft, 5 to 10 minutes. Add garlic and saute until fragrant, about 30 seconds. Remove skillet from heat and cool onion mixture to room temperature.',
            thirdStep: 'Place bread crumbs in a large bowl. Add milk and stir with a fork until combined. Let sit until all of the milk is absorbed into the breadcrumbs, 15 to 20 minutes.',
            fourthStep: 'Combine ground chuck, cooled onion mixture, parsley, Parmesan cheese, eggs, 2 teaspoons salt, black pepper, and cayenne pepper in a bowl. Grab a handful of breadcrumbs and squeeze very gently to remove excess milk. Repeat with remaining breadcrumbs, transfer breadcrumbs to ground chuck mixture, and discard excess milk. Stir ground chuck mixture until evenly combined.',
            fifthStep: 'Turn chuck mixture out into prepared baking dish, and shape meat into a 3x4x10-inch meatloaf. Pour tomato sauce over the loaf and into the bottom of the dish.',
            cookLong: 'This recipe should completely cook medium-sized pork chops in about 10 minutes in an air fryer set to 380 degrees F. Of course, since pork chops vary in thickness, its best to test the temperature before you dig in. An instant read food thermometer inserted into the thickest part of the chop should read at least 145 degrees F.',
            ingredients: '1 tablespoon olive oil, 1 tablespoon butter ,1 onion diced ,salt to taste, 4 cloves garlic minced, 1 ½ cups very dry white bread crumbs, 1 ½ cups milk ,2 pounds ground chuck, ½ cup chopped fresh flat-leaf parsley,2 ounces grated Parmesan cheese ,2 large eggs, beaten ,2 teaspoons salt, 1 teaspoon freshly ground black pepper, 1 pinch cayenne pepper or to taste, 3 cups tomato sauce or to taste',
            Calories: '',
            Fat: '',
            Carbs: '',
            Protein: '',
            photo: 'meatBall.png',
            Rate: '4',
            video: 'https://www.youtube.com/watch?v=ZtZmlK2xLcY',
            comment: [{
            }],
            type: 'latest',
        },
        {
            id: '156252',
            name: 'Honey Garlic Pork Chops',
            cuisine: 'Italian',
            description: 'A quick and simple grilled pork chop that everyone will love featuring a simple and easy glaze made with ketchup, honey, soy sauce, and garlic. and enjoy it dont hesitate to rate it',
            prepTime: '10 mins',
            cookTime: '20 mins',
            totalTime: '30 mins',
            Servings: '6',
            yield: '',
            firstStep: 'Preheat grill for medium heat and lightly oil the grate. Gather ingredients.',
            secondStep: 'Whisk ketchup, honey, soy sauce, and garlic together in a bowl to make a glaze.',
            thirdStep: 'Sear the pork chops on both sides on the preheated grill. Lightly brush glaze onto each side of the chops as they cook; grill until no longer pink in the center, about 7 to 9 minutes per side. An instant-read thermometer inserted into the center should read 145 degrees F (63 degrees C).',
            fourthStep: 'Serve hot and enjoy!',
            fifthStep: 'Top with taco sauce and remaining cheese. Bake until the cheese is melted.',
            cookLong: 'You ll want to grill your pork chops until they are no longer pink in the middle and reach an internal temperature of at least 145 degrees F (63 degrees C). The National Pork Board recommends about eight to 12 minutes for pork chops that are ¾-inch thick. However, every grill is different so it may take some grills longer while some may cook faster. ',
            ingredients: '½ cup ketchup ,2 ⅔ tablespoons honey ,2 tablespoons low-sodium soy sauce, 2 cloves garlic, crushed ,6 (4 ounce) (1-inch thick) pork chops',
            Calories: '',
            Fat: '',
            Carbs: '',
            Protein: '',
            photo: 'Pork.png',
            Rate: '5',
            video: 'https://www.youtube.com/watch?v=6ybbclHqNhI',
            comment: [{
            }],
            type: 'dinner',
        }, {
            id: '156253',
            name: 'Baby Back Ribs',
            cuisine: 'German',
            description: 'These slow cooker ribs are the best Ive had, short of the actual grilling method of course! Theyre easy to make by just cooking them in the slow cooker until tender, covering them with barbeque sauce',
            prepTime: '10 mins',
            cookTime: '4 hrs 15 mins',
            totalTime: '4 hrs 25 mins',
            Servings: '6',
            yield: '',
            firstStep: 'Season ribs with salt and pepper.',
            secondStep: 'Pour 1/2 cup water into the slow cooker, then add ribs. Scatter onion and garlic over top. Cover and cook on Low for 8 hours or High for 4 hours.',
            thirdStep: 'When the ribs are almost finished, preheat the oven to 375 degrees F (190 degrees C).',
            fourthStep: 'Transfer ribs from the slow cooker to a baking sheet; discard onion and garlic. Coat ribs with barbeque sauce.',
            fifthStep: 'Bake ribs in the preheated oven until sauce caramelizes and sticks to meat, 10 to 15 minutes.',
            cookLong: 'Youll find a detailed ingredient list and step-by-step instructions in the recipe below, but lets go over the basics',
            ingredients: '3 pounds baby back ribs, trimmed ,salt and ground black pepper to taste, ½ cup water, ½ onion, sliced ,1 clove garlic minced, 1 (18 ounce) bottle barbeque sauce',
            Calories: '',
            Fat: '',
            Carbs: '',
            Protein: '',
            photo: 'Ribs.png',
            Rate: '3',
            video: 'https://www.youtube.com/watch?v=di0hN1mZuNM',
            comment: [{
            }],
            type: 'dinner',
        }, {
            id: '156254',
            name: 'Eggs with Chorizo',
            cuisine: 'German',
            description: 'This chorizo and egg dish is an appetizing breakfast with spicy flavor. My Mexican husband taught me this simple and delicious recipe that serves 2 people, and I use no more than 6 eggs for both of us.',
            prepTime: '5 mins',
            cookTime: '10 mins',
            totalTime: '15 mins',
            Servings: '2',
            yield: '',
            firstStep: 'Grease a large nonstick skillet with cooking spray; warm over medium-high heat. Cook and stir chorizo in the hot skillet until browned, about 5 minutes.',
            secondStep: 'Whisk together eggs and salt in a medium bowl until combined; pour over chorizo in the skillet; cook and stir until eggs are set, about 5 minutes.',
            thirdStep: '',
            fourthStep: '',
            fifthStep: '',
            cookLong: '',
            ingredients: 'cooking spray, ¼ cup Mexican-style chorizo, or more to taste ,6 large eggs, salt to taste',
            Calories: '',
            Fat: '',
            Carbs: '',
            Protein: '',
            photo: 'Chorizo.png',
            Rate: '5',
            video: 'https://www.youtube.com/watch?v=l9KCAGZk1tk',
            comment: [{
            }],
            type: 'dinner',
        }, {
            id: '156255',
            name: 'Spicy Thai Basil Chicken',
            cuisine: 'German',
            description: 'My version of this classic Thai dish has spectacular taste even with regular basil instead of Thai or holy basil. The sauce actually acts like a glaze as the chicken mixture cooks over high heat.',
            prepTime: '15 mins',
            cookTime: '10 mins',
            totalTime: '25 mins',
            Servings: '2',
            yield: '2 Servings',
            firstStep: 'Gather ingredients.',
            secondStep: 'Whisk chicken broth, oyster sauce, soy sauce, fish sauce, white sugar, and brown sugar together in a bowl until well blended.',
            thirdStep: 'Heat large skillet over high heat. Drizzle in oil. Add chicken and stir fry until it loses its raw color, 2 to 3 minutes.',
            fourthStep: 'Stir in shallots, garlic, and sliced chilies. Continue cooking on high heat until some of the juices start to caramelize in the bottom of the pan, about 2 or 3 more minutes.',
            fifthStep: 'Add about a tablespoon of the sauce mixture to the skillet; cook and stir until sauce begins to caramelize, about 1 minute.',
            sixStep: 'Pour in the rest of the sauce. Cook and stir until sauce has deglazed the bottom of the pan. Continue to cook until sauce glazes onto the meat, 1 or 2 more minutes. Remove from heat.',
            sevenStep: 'Stir in basil. Cook and stir until basil is wilted, about 20 seconds. Serve with rice.',
            cookLong: '',
            ingredients: '⅓ cup chicken broth, 1 tablespoon oyster sauce, 1 tablespoon soy sauceor as needed, 2 teaspoons fish sauce ,1 teaspoon white sugar, 1 teaspoon brown sugar ,2 tablespoons vegetable oil, 1 pound skinless, boneless chicken thighs coarsely chopped ,¼ cup sliced shallots, 4 cloves garlic minced, 2 tablespoons minced Thai chilies Serrano or other hot pepper, 1 cup very thinly sliced fresh basil leaves, 2 cups hot cooked rice',
            Calories: '',
            Fat: '',
            Carbs: '',
            Protein: '',
            photo: 'Thai-Basil-Chicken.png',
            Rate: '4.5',
            video: 'https://www.youtube.com/watch?v=entMQMVK4go',
            comment: [{
            }],
            type: 'dinner',
        },

        {
            id: '156256',
            name: 'Bruschetta with Mozzarella',
            cuisine: 'Italian',
            description: 'Some people call it bruschetta caprese–we simply call it delicious! This is a quick and easy appetizer with classic Italian flavors that’ll never let you down.',
            prepTime: '10 mins',
            cookTime: '1 mins',
            totalTime: '11 mins',
            Servings: '4',
            yield: '',
            firstStep: 'Place tomatoes, mozzarella, sliced basil, garlic, 1 tablespoon olive oil, and balsamic vinegar in a bowl, and fold until well combined. Season to taste with salt and pepper. Set aside.',
            secondStep: 'Set an oven rack about 6 inches from the heat source and preheat the ovens broiler. Brush baguette slices with remaining olive oil until lightly coated. Arrange in a single layer on a baking sheet; season with salt. Broil until lightly browned, about 1 minute, being careful not to burn.',
            thirdStep: 'Spoon tomato mixture onto toasted baguette immediately before serving, and garnish with fresh basil leaves.',
            fourthStep: '',
            fifthStep: '',
            cookLong: '',
            ingredients: '2 cups halved grape tomatoes,well drained ,4 ounces fresh mozzarella cheese, cut into 1/4-inch cubes ,2 tablespoons thinly sliced fresh basil leaves ,2 cloves garlic pressed ,1 1/2 tablespoons olive oil, divided	, 1/2 tablespoon balsamic vinegar ,salt and freshly ground black pepper to taste ,8 (1/2-inch thick) diagonal slices baguette ,fresh basil leaves for garnish (optional)',
            Calories: '233',
            Fat: '8',
            Carbs: '33',
            Protein: '8',
            photo: 'Bruschetta.png',
            Rate: '3.5',
            video: 'https://www.youtube.com/watch?v=a0C7E6xE-0o',
            comment: [{
            }],
            type: 'other',

        },
        {
            id: '156257',
            name: 'Pasta alla Trapanese (Sicilian Tomato Pesto)',
            cuisine: 'Italian',
            description: 'Im excited to share my version of pasta alla Trapanese, featuring Sicilys amazing tomato pesto. I love the green Genovese-style pesto, but when super-sweet cherry tomatoes are in season, I really believe this is the best pesto.',
            prepTime: '20 mins',
            cookTime: '15 mins',
            totalTime: '35 mins',
            Servings: '8',
            yield: '',
            firstStep: 'Bring about 2 cups of water to a boil, remove from the heat, and stir in almonds; let sit for 3 to 4 minutes. Drain, and once cool enough to handle, rub skins off with your hands; alternately; transfer drained almonds to a kitchen towel, then fold up the towel and rub almonds until skins come off. ',
            secondStep: 'Crush sliced garlic with kosher salt in a mortar and pestle into a smooth paste. Alternately, place garlic on a board and sprinkle kosher salt on top; use the flat side of the knife to flatten, mash, and scrape the garlic and salt mixture until it is a smooth paste.',
            thirdStep: 'Add peeled almonds to the jar of a blender, followed by the cheese, basil, mint, garlic paste, oil, and tomatoes. Add the ingredients in this order, so that the almonds and cheese have a chance to grind before the wetter ingredients mix in.',
            fourthStep: 'Begin to pulse blender on and off until almonds and cheese are ground, then continue to pulse until remaining ingredients are incorporated. Blend on high until the pesto is as coarse or smooth as you like. ',
            fifthStep: 'Taste for salt, and adjust. Set aside while pasta is cooking. ',
            sixStep: 'Bring a large pot of lightly salted water to a boil. Cook busiate pasta in the boiling water, stirring occasionally, until tender yet firm to the bite, about 12 minutes. Transfer pasta into a bowl with a strainer. Reserve starchy cooking liquid. ',
            sevenStep: 'Add about 1/3 cup of the pasta water into the bowl, and then transfer in the pesto, along with a large pinch of salt, and toss to coat. More pasta water can be added to adjust the texture. Once mixed, add another optional handful of cheese, and toss one last time. Serve immediately.',
            cookLong: '',
            ingredients: '1/2 cup whole roasted almonds, 4 cloves garlic, 1 teaspoon kosher salt plus more to taste ,1 cup grated pecorino Romano cheese plus more to taste ,1 cup packed fresh basil leaves ,4 mint leaves (optional) ,1/2 cup extra virgin olive oil ,1 pound red cherry tomatoes or red grape tomatoes ,1 pound busiate pasta or other curly shaped pasta such as fusilli',
            Calories: '312',
            Fat: '21',
            Carbs: '22',
            Protein: '9',
            photo: 'Pasta.png',
            Rate: '4',
            video: 'https://www.youtube.com/watch?v=vMshCdGwK1g',
            comment: [{
            }],
            type: 'other',

        },
        {
            id: '156258',
            name: 'Chef Johns Italian Meatballs',
            cuisine: 'Italian',
            description: 'This Italian meatball recipe is very easy to make, and since we skip the messy step of pan-frying the meatballs, it becomes downright simple. Here I use a standard half-beef/half-pork mixture.',
            prepTime: '20 mins',
            cookTime: '35 mins',
            totalTime: '2 hrs 15 mins',
            Servings: '8',
            yield: '',
            firstStep: 'Cover a baking sheet with foil and spray lightly with cooking spray. Soak bread crumbs in milk in a small bowl for 20 minutes.',
            secondStep: 'Meanwhile, heat olive oil in a skillet over medium heat. Add onion; cook and stir until onion has softened and turned translucent, about 5 minutes. Reduce heat to low and continue cooking and stirring until onion is very tender, about 15 minutes more.',
            thirdStep: 'Gently stir beef and pork together in a large bowl. Add onions, bread crumb mixture, eggs, Parmesan cheese, parsley, garlic, salt, black pepper, Italian herb seasoning, and red pepper flakes; mix together using a rubber spatula until combined. Cover and refrigerate for about one hour.',
            fourthStep: 'Preheat the oven to 425 degrees F (220 degrees C).',
            fifthStep: 'Form mixture into balls about 1 1/2 inches in diameter; arrange in a single layer on the prepared baking sheet.',
            sixStep: 'Bake in the preheated oven until browned and cooked through, 15 to 20 minutes.',
            cookLong: '',
            ingredients: '½ cup milk,2 tablespoons olive oil,1 onion diced,1 pound ground pork,2 eggs,2 tablespoons grated Parmesan cheese,¼ bunch fresh parsley chopped,3 cloves garlic, crushed,2 teaspoons salt,1 teaspoon ground black pepper,1 teaspoon dried Italian herb seasoning,½ teaspoon red pepper flakes',
            Calories: '390',
            Fat: '31',
            Carbs: '5',
            Protein: '21',
            photo: 'Meatbal.png',
            Rate: '5',
            video: 'https://www.youtube.com/watch?v=vu3k-bEcuBA',
            comment: [{
            }],
            type: 'other',

        },
        {
            id: '156259',
            name: 'Easy Chicken Street Tacos',
            cuisine: 'Mexican',
            description: 'I go to my local Mexican Market and buy "pollo para asar" which translates to "chicken to grill." This chicken is seasoned and ready to grill. These delicious tacos are easy to make and topped with cilantro and onions.',
            prepTime: '10 mins',
            cookTime: '8 mins',
            totalTime: '18 mins',
            Servings: '8',
            yield: '8 tacos',
            firstStep: 'Preheat an outdoor grill for medium-high heat and lightly oil the grate.',
            secondStep: 'Grill chicken, turning occasionally, until juices run clear and chicken is no longer pink at the center, about 7 minutes. An instant-read thermometer, inserted near the center, should read at least 165 degrees F (74 degrees C).',
            thirdStep: 'Heat corn tortillas until soft and pliable in the microwave, about 1 minute. Top with chicken, onions, and cilantro.',
            cookLong: '',
            ingredients: '1 pound pollo para asar (seasoned, boneless, skinless chicken,1 onion diced,1/2 cup chopped cilantro,8 corn tortillas',
            Calories: '165',
            Fat: '5',
            Carbs: '12',
            Protein: '18',
            photo: 'tacos.png',
            Rate: '4',
            video: 'https://www.youtube.com/watch?v=kvOsKDEbBQw',
            comment: [{
            }],
            type: 'other',

        },
        {
            id: '156260',
            name: 'Guacamole',
            cuisine: 'Mexican',
            description: 'Mexican Guacamole is a creamy and zesty dip made from ripe avocados, tomatoes, onions, cilantro...bursting with vibrant flavors and perfect for dipping tortilla chips or complementing various dishes.',
            prepTime: '15 mins',
            cookTime: '',
            totalTime: '15 mins',
            Servings: '4',
            yield: '',
            firstStep: 'Mash avocados, lime juice, and salt together in a medium bowl; mix in tomatoes, onion, cilantro, and garlic. Stir in cayenne pepper.',
            secondStep: 'Serve immediately, or cover and refrigerate for 1 hour for improved flavor.',
            cookLong: '',
            ingredients: '3 avocados - peeled pitted and mashed,1 lime juiced,1 teaspoon salt,2 roma (plum) tomatoes diced,½ cup diced onion,3 tablespoons chopped fresh cilantro,1 teaspoon minced garlic,1 pinch ground cayenne pepper (Optional)',
            Calories: '262',
            Fat: '22',
            Carbs: '18',
            Protein: '4',
            photo: 'Guacamole.png',
            Rate: '5',
            video: 'https://www.youtube.com/watch?v=4ff_uugBaAY',
            comment: [{
            }],
            type: 'other',

        },
        {
            id: '156261',
            name: 'Simple Crème Brûlée Dessert',
            cuisine: 'French',
            description: 'This easy crème brûlée recipe is rich and creamy. It should still be jiggly in the center when you remove it from the oven. To serve, use a spoon to crack the crisp sugar topping open to reveal the creamy dessert underneath.',
            prepTime: '15 mins',
            cookTime: '55 mins',
            totalTime: '3 hrs 10 mins',
            Servings: '2',
            yield: '',
            firstStep: 'Preheat the oven to 350 degrees F (175 degrees C).',
            secondStep: 'Whisk together cream and 3 tablespoons sugar in a microwave-safe bowl until combined. Cook in the microwave until warm, 1 to 2 minutes; whisk again to dissolve sugar. Whisk in egg yolks and vanilla until smooth.',
            thirdStep: 'Pour cream mixture into 2 ramekins set in a roasting pan. Pour enough hot water into the pan to reach halfway up the sides of the ramekins.',
            fourthStep: 'Bake in the preheated oven until custard is set but slightly jiggly in the center when shaken, about 50 minutes. Remove ramekins from hot water and chill in the refrigerator until cold, at least 2 hours.',
            fifthStep: 'Sprinkle 1 tablespoon sugar evenly over the top of each dessert. Use a kitchen torch to melt and lightly toast sugar topping until brown and bubbly, about 30 seconds. Let sugar topping cool to harden before serving.',
            cookLong: '',
            ingredients: '1 cup heavy cream,3 tablespoons white sugar,3 large egg yolks,¼ teaspoon vanilla extract,2 tablespoons white sugar, divided',
            Calories: '612',
            Fat: '51',
            Carbs: '36',
            Protein: '6',
            photo: 'Crème.png',
            Rate: '3.5',
            video: 'https://www.youtube.com/watch?v=ZPz7FP15OCs',
            comment: [{
            }],
            type: 'other',

        },
        {
            id: '156262',
            name: 'Barbacoa-Style Shredded Beef',
            cuisine: 'Mexican',
            description: 'This barbacoa recipe cooks the beef in a flavorful barbacoa sauce in the slow cooker until its fall-apart tender and easy to shred. Its similar to what youd get at Chipotles and perfect for nachos, tacos, and burritos.',
            prepTime: '35 mins',
            cookTime: '8 hrs 10 mins',
            totalTime: '8 hrs 55 mins',
            Servings: '8',
            yield: '',
            firstStep: 'Season beef chunks with salt and pepper on all sides.',
            secondStep: 'Heat oil in a large skillet over medium-high heat. Working in batches, cook and stir beef until browned, 4 to 5 minutes per batch. Transfer browned beef to a slow cooker.',
            thirdStep: 'Mix broth, vinegar, lime juice, chipotle peppers, garlic, cumin, oregano, and cloves together in a bowl until well combined. Season mixture with salt and pepper and pour over beef in the slow cooker. Stir in bay leaves.',
            fourthStep: 'Cook on Low until beef is fork-tender, 8 to 10 hours. Discard bay leaves. Remove beef from the cooker and shred using two forks.',
            fifthStep: 'Return beef to the slow cooker and stir to coat with sauce. Let marinate for at least 10 minutes before serving.',
            cookLong: '',
            ingredients: '1 (3 pound) beef chuck roast, cut into 6 to 8 chunks,salt and ground black pepper to taste,2 tablespoons vegetable oil,½ cup beef broth,¼ cup apple cider vinegar,¼ cup fresh lime juice, 4 chipotle peppers in adobo sauce chopped,5 cloves garlic chopped,1 tablespoon ground cumin,1 tablespoon dried oregano,¼ teaspoon ground cloves,3 large bay leaves',
            Calories: '303',
            Fat: '23',
            Carbs: '3',
            Protein: '20',
            photo: 'Barbacoa.png',
            Rate: '5',
            video: 'https://www.youtube.com/watch?v=ct4_vsJizG4',
            comment: [{
            }],
            type: 'other',
        },
        {
            id: '156263',
            name: 'Steamed Fish with Ginger',
            cuisine: 'Chinese',
            description: ' Steamed Fish with Ginger is a light and fragrant Cantonese dish featuring fresh fish, ginger, and scallions, all gently steamed to perfection. Its a culinary masterpiece known for its delicate flavors and healthful qualities.',
            prepTime: '15 mins',
            cookTime: '10 mins',
            totalTime: '25 mins',
            Servings: '2',
            yield: '2 servings',
            firstStep: 'Pat halibut dry with paper towels. Rub both sides of fillet with salt. Scatter the ginger over the top of the fish and place onto a heatproof ceramic dish.',
            secondStep: 'Place into a bamboo steamer set over several inches of gently boiling water, and cover. Gently steam for 10 to 12 minutes.',
            thirdStep: 'Pour accumulated water out of the dish and sprinkle the fillet with green onion. Drizzle both soy sauces over the surface of the fish.',
            fourthStep: 'Heat peanut and sesame oils in a small skillet over medium-high heat until they begin to smoke. When the oil is hot, carefully pour on top of the halibut fillet. The very hot oil will cause the green onions and water on top of the fish to pop and spatter all over; be careful. Garnish with cilantro sprigs and serve immediately.',
            cookLong: '',
            ingredients: '1 pound halibut fillet,1 teaspoon coarse sea salt or kosher salt,1 tablespoon minced fresh ginger,3 tablespoons thinly sliced green onion,1 tablespoon dark soy sauce,1 tablespoon light soy sauce,1 tablespoon peanut oil,2 teaspoons toasted sesame oil,¼ cup lightly packed fresh cilantro sprigs',
            Calories: '361',
            Fat: '17',
            Carbs: '2',
            Protein: '48',
            photo: 'FishwithGinger.png',
            Rate: '4',
            video: 'https://www.youtube.com/watch?v=sMG9a3XbdZQ',
            comment: [{
            }],
            type: 'other',

        },

        {
            id: '156264',
            name: 'Meat Pie',
            cuisine: 'French',
            description: 'This meat pie is delicious! I got it from my husbands mother. She is French so I believe this is a French meat pie recipe. Beef, pork, and potato are all nicely spiced and baked together. Its yummy and pretty easy to make too! Its best served fresh.',
            prepTime: '25 mins',
            cookTime: '25 mins',
            totalTime: '50 mins',
            Servings: '8',
            yield: '1 9-inch pie',
            firstStep: 'Preheat the oven to 425 degrees F (220 degrees C).',
            secondStep: 'Place potato in a saucepan with enough water to cover. Bring to a boil, and cook until tender, about 5 minutes. Drain, mash, and set aside.',
            thirdStep: 'Meanwhile, crumble ground beef and pork into a large saucepan. Add onion, garlic, mustard powder, thyme, sage, cloves, salt, and black pepper. Stir in water. Cook over medium heat, stirring, until meat is evenly browned.',
            fourthStep: 'Remove from the heat and mix in mashed potato.',
            fifthStep: 'Ease one pie crust into a 9-inch pie plate. Fill with meat mixture, then top with the remaining pie crust. Trim any excess dough, then crimp the edges with the tines of a fork to seal. Prick top crust a few times with a knife to vent steam. Cover the edges of the crust with aluminum foil.',
            sixStep: 'Bake in the preheated oven until crust is browned, about 25 minutes.',
            cookLong: '',
            ingredients: '1 medium potato, peeled and cubed,½ pound ground beef,½ pound ground pork,½ cup chopped onion,⅓ clove garlic, chopped,½ teaspoon mustard powder,½ teaspoon dried thyme,¼ teaspoon dried sage,¼ teaspoon ground cloves,1 teaspoon salt,¼ teaspoon ground black pepper,¼ cup water,1 (15 ounce) package refrigerated pie crusts',
            Calories: '381',
            Fat: '24',
            Carbs: '28',
            Protein: '14',
            photo: 'MeatPie.png',
            Rate: '5',
            video: 'https://www.youtube.com/watch?v=Yj4imWyGp-Q',
            comment: [{
            }],
            type: 'other',

        },
        {
            id: '156265',
            name: 'Lobster Thermidor',
            cuisine: 'French',
            description: 'This stunning lobster Thermidor is surprisingly simple to make. Lobster shells are stuffed with cooked lobster in a creamy white wine sauce, then topped with Parmesan cheese and broiled until golden.',
            prepTime: '30 mins',
            cookTime: '10 mins',
            totalTime: '40 mins',
            Servings: '2',
            yield: '',
            firstStep: 'Cut lobster in half lengthwise, and remove any meat from the claws, tail, and head. Cut meat into pieces and place back into the shells.',
            secondStep: 'Melt butter in a large skillet over medium heat. Add shallot; cook and stir until tender. Mix in fish stock, white wine, and cream. Bring to a boil, and cook until reduced by half. Mix in parsley, lemon juice, mustard, salt, and pepper.',
            thirdStep: 'Preheat your ovens broiler.',
            fourthStep: 'Place stuffed lobster halves on a broiling pan or baking sheet. Spoon sauce over the meat and sprinkle with Parmesan cheese.',
            fifthStep: 'Broil in the preheated oven until just golden brown, 3 to 4 minutes. Serve immediately.',
            cookLong: '',
            ingredients: '1 medium (1 1/2 pound) cooked lobster,2 tablespoons butter,1 shallot, finely chopped,1 ⅜ cups fresh fish stock,¼ cup white wine,¼ cup heavy cream,½ teaspoon hot English mustard,2 tablespoons chopped fresh parsley,1 tablespoon fresh lemon juice,salt and freshly ground black pepper to taste,¼ cup freshly grated Parmesan cheese',
            Calories: '653',
            Fat: '28',
            Carbs: '14',
            Protein: '77',
            photo: 'Lobster.png',
            Rate: '3',
            video: 'https://www.youtube.com/watch?v=JyWMN6YSu5A',
            comment: [{
            }],
            type: 'other',

        },

        {
            id: '156266',
            name: 'Quick Beef Stir-Fry',
            cuisine: 'Chinese',
            description: 'Quick Beef Stir-Fry is a fast and flavorful Asian-inspired dish featuring thinly sliced beef, vibrant vegetables, and a savory sauce. Sear the beef, toss in the veggies, and stir-fry it all together for a delicious meal ready in minutes.',
            prepTime: '15 mins',
            cookTime: '10 mins',
            totalTime: '25 mins',
            Servings: '4',
            yield: '4 servings',
            firstStep: 'Gather all ingredients.',
            secondStep: 'Heat vegetable oil in a large wok or skillet over medium-high heat; cook and stir beef until browned, 3 to 4 minutes.',
            thirdStep: 'Move beef to the side of the wok and add broccoli, bell pepper, carrots, green onion, and garlic to the center of the wok. Cook and stir vegetables for 2 minutes.',
            fourthStep: 'Stir beef into vegetables and season with soy sauce and sesame seeds. Continue to cook and stir until vegetables are tender, about 2 more minutes.',
            fifthStep: 'Serve hot and enjoy!',
            cookLong: '',
            ingredients: '2 tablespoons vegetable oil,1 pound beef sirloin, cut into 2-inch strips,1 ½ cups fresh broccoli florets,1 red bell pepper, cut into matchsticks,2 carrots, thinly sliced,1 green onion chopped,1 teaspoon minced garlic,2 tablespoons soy sauce,2 tablespoons sesame seeds toasted',
            Calories: '268',
            Fat: '16',
            Carbs: '9',
            Protein: '23',
            photo: 'Stir-Fry.png',
            Rate: '5',
            video: 'https://www.youtube.com/watch?v=NUmy4B_AY2c',
            comment: [{
            }],
            type: 'other',

        },
        {
            id: '156267',
            name: 'Taiwanese Popcorn Chicken',
            cuisine: 'Chinese',
            description: 'These Taiwanese popcorn chicken bites are incredibly delicious. Five-spice, ginger, and soy sauce flavor bite-sized pieces of chicken before theyre dipped in tempura mix and fried until golden and crispy.',
            prepTime: '30 mins',
            cookTime: '15 mins',
            totalTime: '55 mins',
            Servings: '6',
            yield: '',
            firstStep: 'Mix chicken, garlic, soy sauce, ginger, five-spice powder, white pepper, salt, vinegar, and cayenne pepper together in a large bowl until well combined. Let marinate for 10 minutes.',
            secondStep: 'Heat oil in a deep-fryer or large saucepan to 400 degrees F (200 degrees C).',
            thirdStep: 'Whisk egg in a small bowl until smooth. Place dry tempura mix into a second small bowl. Dip chicken pieces one at a time into egg, then dredge in tempura mix, shaking off any excess.',
            fourthStep: 'Working in batches, lower chicken carefully into hot oil and fry until golden brown, 5 to 8 minutes. Transfer to a paper towel-lined plate to drain and season with salt and pepper.',
            fifthStep: 'Transfer chicken to a platter and garnish with basil leaves and green onions.',
            cookLong: '',
            ingredients: '1 ½ pounds boneless chicken thighs, cut into bite-size pieces,2 cloves garlic finely chopped,1 tablespoon soy sauce,2 teaspoons grated ginger,1 teaspoon five-spice powder,1 teaspoon ground white pepper or to taste,1 teaspoon salt or to taste,½ teaspoon rice vinegar,½ teaspoon cayenne pepper,1 large egg,1 cup tempura batter mix, dry, or as needed,2 cups peanut oil for frying, or as needed,1 bunch Thai basil chopped,2 green onions chopped',
            Calories: '940',
            Fat: '92',
            Carbs: '8',
            Protein: '22',
            photo: 'Popcorn.png',
            Rate: '4.5',
            video: 'https://www.youtube.com/watch?v=no3S5nce_6Q',
            comment: [{
            }],
            type: 'other',

        },
    ])
})